apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorilla-deployment
  labels:
    app: gorilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorilla
  template:
    metadata:
      labels:
        app: gorilla
    spec:
      containers:
      - name: gorilla
        image: gcr.io/kubes-369319/gorilla_mux_api_8000
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: gorilla
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

